# Generated by Django 5.0.7 on 2024-09-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='charity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='cuisine',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='hosting_organization',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
